export enum PostponementReason {
  CUSTOMER_UNREACHABLE = 'CUSTOMER_UNREACHABLE',
  CUSTOMER_REQUESTED_RESCHEDULE = 'CUSTOMER_REQUESTED_RESCHEDULE',
  CUSTOMER_REFUSED_DELIVERY_TEMPORARILY = 'CUSTOMER_REFUSED_DELIVERY_TEMPORARILY',
  INCORRECT_ADDRESS = 'INCORRECT_ADDRESS',
  OUT_OF_ROUTE_TIME = 'OUT_OF_ROUTE_TIME',
  WEATHER_OR_ROAD_BLOCKAGE = 'WEATHER_OR_ROAD_BLOCKAGE',
  VEHICLE_BREAKDOWN = 'VEHICLE_BREAKDOWN',
  CASH_NOT_AVAILABLE = 'CASH_NOT_AVAILABLE',
  OTHER = 'OTHER',
}
