version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: logistics_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics_ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logistics_ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistics_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: logistics_ecommerce_db
      DB_SYNCHRONIZE: false
      JWT_SECRET: super_secret_jwt_key_egypt_logistics_2026_x8891
      JWT_EXPIRATION: 7d

volumes:
  pgdata:
